# Generated by Django 4.2 on 2023-10-08 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booktest', '0003_alter_heroinfo_hbook'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heroinfo',
            name='hbook',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booktest.bookinfo', verbose_name='所属书籍'),
        ),
    ]
