# Generated by Django 4.2 on 2023-07-13 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='mobile',
            field=models.CharField(default=18570488064, max_length=11, unique=True, verbose_name='手机号'),
            preserve_default=False,
        ),
    ]
