# Generated by Django 4.2 on 2023-10-18 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_address_user_default_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='distinct',
            new_name='district',
        ),
    ]
