# Generated by Django 4.2 on 2023-09-15 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('areas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='areas',
            options={},
        ),
    ]
