# Generated by Django 4.2 on 2023-12-06 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_alter_goods_desc_detail_alter_goods_desc_pack_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='skuimage',
            table='tb_sku_image',
        ),
    ]
